--CREATE DATABASE IF NOT EXISTS HOTEL;
--USE CLIENTES;

CREATE TABLE IF NOT EXISTS USUARIOS (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    USUARIO_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

INSERT INTO USUARIOS (NOME, SENHA) VALUES ('fidel', '123');
INSERT INTO CLIENTES (NOME, CPF, USUARIO_ID) VALUES ('Fidel', '0992828822', 1);

INSERT INTO USUARIOS (NOME, SENHA) VALUES ('adriano', '123');
INSERT INTO CLIENTES (NOME, CPF, USUARIO_ID) VALUES ('Adriano', '0992828822', 2);

INSERT INTO USUARIOS (NOME, SENHA) VALUES ('ygor', '123');
INSERT INTO CLIENTES (NOME, CPF, USUARIO_ID) VALUES ('Ygor', '0992828822', 3);

INSERT INTO USUARIOS (NOME, SENHA) VALUES ('silvio', '123');
INSERT INTO CLIENTES (NOME, CPF, USUARIO_ID) VALUES ('Silvio', '0992828822', 4);

INSERT INTO USUARIOS (NOME, SENHA) VALUES ('anderson', '123');
INSERT INTO CLIENTES (NOME, CPF, USUARIO_ID) VALUES ('Anderson', '0992828822', 5);